### ISSUE TITLE
SSL errors in setup.py

### ISSUE THREAD

**Issue by JavierCVilla** [rdemaria/pytimber#33]
Hi all,

Trying to install pytimber-2.2.3 from source just running the command:

```
python setup.py 
```

I get this error trace:

```
Traceback (most recent call last):
  File "setup.py", line 83, in <module>
    cmmnbuild_url + 'repository/archive.zip?ref=master#egg=cmmnbuild_dep_manager-' + cmmnbuild_version()
  File "setup.py", line 39, in cmmnbuild_version
    file = urlopen(init)
  File "/my/path/python-2.7.10-jzfq36hljqkkjyuumivx4u4nefo73zyi/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/my/path/python-2.7.10-jzfq36hljqkkjyuumivx4u4nefo73zyi/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/my/path/python-2.7.10-jzfq36hljqkkjyuumivx4u4nefo73zyi/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/my/path/python-2.7.10-jzfq36hljqkkjyuumivx4u4nefo73zyi/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/my/path/python-2.7.10-jzfq36hljqkkjyuumivx4u4nefo73zyi/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/my/path/python-2.7.10-jzfq36hljqkkjyuumivx4u4nefo73zyi/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/my/path/python-2.7.10-jzfq36hljqkkjyuumivx4u4nefo73zyi/lib/python2.7/httplib.py", line 1274, in connect
    server_hostname=server_hostname)
  File "/my/path/python-2.7.10-jzfq36hljqkkjyuumivx4u4nefo73zyi/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/my/path/python-2.7.10-jzfq36hljqkkjyuumivx4u4nefo73zyi/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/my/path/python-2.7.10-jzfq36hljqkkjyuumivx4u4nefo73zyi/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
``` 

Is there something that I'm doing wrong?

By other hand, I was wondering if it is possible to avoid py-timber to install cmmnbuild by itself and provide my own installed package.

**Comment by levens** [comment]
Hi Javier,

Do you get a certificate warning when visiting https://gitlab.cern.ch/ ? You might have to install the CERN host certificates from https://cern.ch/ca/

You can use your own version of cmmnbuild_dep_manager, but at this lookup in the setup.py is required to check the version. At the moment there is no way to bypass that. Also you must be on the CERN network to download the required jars.

Cheers,

**Comment by JavierCVilla** [comment]
Hi @levens 

> Do you get a certificate warning when visiting https://gitlab.cern.ch/ ? You might have to install the CERN host certificates from https://cern.ch/ca/

Yes, I'm working inside the CERN network. 

> You can use your own version of cmmnbuild_dep_manager, but at this lookup in the setup.py is required to check the version. At the moment there is no way to bypass that. Also you must be on the CERN network to download the required jars.

So, although I use my own cmmnbuild_dep_manager installed package, is it mandatory to check the version from a remote file? 
Couldn't be possible to check it from the file located in the path that I provided with the cmmnbuild installation?

I'm trying to add `py-timber` as a supported package in [Spack](https://github.com/LLNL/spack/).

**Comment by levens** [comment]
Hi Javier,

The lookup is not for the locally installed version (as this is handed by pip/setuptools). Because cmmnbuild_dep_manager is not on PyPI, we have to use the "dependency links" feature of setuptools. This requires the current remote version in master to be known as it has to be in the URL string. Otherwise, we would have to link to a specific tag and update every package when the version of cmmnbuild_dep_manager changes. Which would be a pain.

I think when they used it on SWAN they had a similar issue. I'll see if I can dig up the email thread.

Cheers,

**Comment by levens** [comment]
Hi @JavierCVilla,

I have published cmmnbuild_dep_manager on PyPI:

https://pypi.python.org/pypi/cmmnbuild-dep-manager

This removes the need to make this check. Once @rdemaria merges #34, can you please test again?

Cheers,

**Comment by rdemaria** [comment]
I merged, but I could not test...

**Comment by levens** [comment]
Hi @rdemaria,

At least the standard install (i.e. pip install ...) on a fresh Python environment works OK. Let's see if @JavierCVilla's specific installation works OK.

Cheers,

**Comment by rdemaria** [comment]
I think will register to pypi as well...

On 18 Feb 2017 17:31, "Tom Levens" <notifications@github.com> wrote:

Hi @rdemaria <https://github.com/rdemaria>,

At least the standard install (i.e. pip install ...) on a fresh Python
environment works OK. Let's see if @JavierCVilla
<https://github.com/JavierCVilla>'s specific installation works OK.

Cheers,

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/rdemaria/pytimber/issues/33#issuecomment-280856645>,
or mute
the thread

**Comment by levens** [comment]
Hi @rdemaria,

If you are planning on releasing PyTimber, you may be interested in this small script I wrote to automate the release. It automatically tags the current revision and releases it to PyPI:

https://gitlab.cern.ch/scripting-tools/cmmnbuild-dep-manager/blob/master/release.sh

Cheers,

**Comment by JavierCVilla** [comment]
Hi @levens and @rdemaria ,

thank you very much for your work! I have already installed the package from source without any problem. Soon, it will be supported to be installed using Spack.

Thanks a lot!

**Comment by rdemaria** [comment]
pip install pytimber

works now! ;-)
