### ISSUE TITLE
Querying time interval with LoggingDB

### ISSUE THREAD

**Issue by pierrebarroca** [rdemaria/pytimber#77]
When I do a query for given time interval I retrieve empty data.

This issue can be easily replicated with the LHC_Panel notebook in the examples
querying a single measurement like this on cell 6
`now=time.time()
now_minus_a_day = now - 3600*24
ib1="LHC.BCTDC.A6R4.B1:BEAM_INTENSITY"
ib2="LHC.BCTDC.A6R4.B2:BEAM_INTENSITY"
nrg="LHC.BOFSU:OFSU_ENERGY"
data=db.get(ib1,now_minus_a_day,now)`
 
gives 
`{'LHC.BCTDC.A6R4.B1:BEAM_INTENSITY': (array([], dtype=float64),
  array([], dtype=float64))}`

querying a single datetime works

**Comment by pierrebarroca** [comment]
Here is an example.

![Screenshot_2020-06-16 PytimberEXAMPLECO2 - Jupyter Notebook](https://user-images.githubusercontent.com/6313800/84756944-c661c080-afc3-11ea-8d4d-885d6211c6aa.png)

**Comment by rdemaria** [comment]
With one timestamp you get the last data point before the timestamp. Are you sure this record is in between ts1 and ts2? What happens when the data range is larger?

**Comment by pierrebarroca** [comment]
I got the issue now. Thank you for the help.
